- name: Kubernetes - Download GPG keyring
  dest: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}
  group: root
  mode: '0644'
  owner: root
  url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
  ansible.builtin.get_url:

- name: Add an apt signing key for Kubernetes
  args:
    creates: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg
  changed_when: false
  ansible.builtin.command: gpg --batch --yes --dearmor /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}

- name: Set file permissions for keyring
  group: root
  mode: '0644'
  owner: root
  path: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg
  ansible.builtin.file:

- name: update kubernetes list file
  ansible.builtin.shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Adding apt repository for Kubernetes
  filename: kubernetes-{{ kubernetes_version }}.list
  repo: deb [signed-by=/etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
  state: present
  ansible.builtin.apt_repository:

- name: Find latest kubernetes version in apt
  allow_change_held_packages: true
  update_cache: true
  ansible.builtin.apt:
