- name: Post worker node join hooks
  run_once: true
  when:
  - inventory_hostname in groups['worker_nodes']
  - kubernetes_hookfiles.post_workers is defined
  with_items: "{{ kubernetes_hookfiles.post_workers }}"
  ansible.builtin.include_tasks: "{{ item }}"
