containerd_mirror: "{% if ansible_facts['os_family'] == 'Debian' %}https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}{% else %}https://download.docker.com/linux/centos/$releasever/$basearch/stable{% endif %}"
containerd_credentials: []

# This is deprecated starting in containerd 2.0.0
# containerd_credentials:
# - username: "username"
#   password: "password"
#   registry: "https://index.docker.io/v1/"

# Deprecated as of containerd version 2.0.0
# This configuration works for versions below 2.2.0
# Instructs containerd to use registry mirrors. Multiple enpoints can be defined in a list.
# Reference:
# https://github.com/containerd/containerd/blob/main/docs/cri/registry.md
# containerd_registry_mirrors:
# - registry: docker.io
#   endpoints:
#   - https://dockermirror.example.com:5001
# - registry: quay.io
#   endpoints:
#   - https://quaymirror.example.com:5002
# - registry: registry.k8s.io
#   endpoints:
#   - https://k8smirror.example.com:5003

# Used for containerd versions greater than or equal to 2.2.0
# Refer to containerd's documentation for host and server options:
# https://github.com/containerd/containerd/blob/main/docs/hosts.md
# containerd_registry_mirrors:
# - registry: docker.io
#   extra_files:
#   - name: ca.pem
#     content: |
#       file content
#   - name: client.cert
#     content: |
#       file content
#   - name: client.key
#     content: |
#       file content
#   hosts:
#   - host: "https://dockermirror.example.com:5001"
#     ca: "ca.pem"
#     capabilities: '["pull", "resolve"]'
#     client: '[["client.cert", "client.key"]]'
#     dial_timeout: "5s"
#     override_path: false
#     skip_verify: false
#     headers:
#     - name: Authorization
#       value: "Basic <base64 encoded username:password>"
#   server:
