- name: Setup local kubeconfig file
  block:
  - name: Read ca.crt from first control plane
    delegate_to: "{{ kubernetes_first_kube_control_plane }}"
    register: ca_crt_file
    run_once: true
    ansible.builtin.slurp:
      src: /etc/kubernetes/pki/ca.crt

  - name: Set ca_crt variable
    delegate_to: "{{ kubernetes_first_kube_control_plane }}"
    run_once: true
    ansible.builtin.set_fact:
      ca_crt: "{{ ca_crt_file.content | b64decode }}"

  - name: Make sure ~/.kube directory exists on localhost
    become: false
    delegate_to: localhost
    run_once: true
    ansible.builtin.file:
      dest: ~/.kube
      state: directory
      mode: '0700'

  - name: Write ca.crt to file ~/ca.crt
    become: false
    delegate_to: localhost
    run_once: true
    ansible.builtin.copy:
      content: "{{ ca_crt }}"
      dest: ~/.kube/{{ kubernetes_cluster_name }}-ca.crt
      mode: '0600'

  - name: Set local kubeconfig values
    become: false
    changed_when: true
    delegate_to: localhost
    register: setup_kubeconfig_int128
    run_once: true
    ansible.builtin.shell:
      cmd: |
        kubectl config set-cluster {{ kubernetes_cluster_name }} \
          --server=https://{{ kubernetes_api_endpoint }}:{{ kubernetes_api_port }} \
          --certificate-authority=$HOME/.kube/{{ kubernetes_cluster_name }}-ca.crt

        kubectl config set-credentials oidc:{{ kubernetes_cluster_name }} \
          --exec-command=kubelogin \
          --exec-arg=get-token \
          --exec-arg=--oidc-issuer-url \
          --exec-arg="{{ kubernetes_oidc_issuer_url }}" \
          --exec-arg=--oidc-client-id \
          --exec-arg="{{ kubernetes_oidc_client_id }}" \
          --exec-api-version=client.authentication.k8s.io/v1beta1

        kubectl config set-context {{ kubernetes_cluster_name }} \
          --cluster={{ kubernetes_cluster_name }} \
          --user=oidc:{{ kubernetes_cluster_name }}

        kubectl config use-context {{ kubernetes_cluster_name }}

  rescue:
  - name: Output setup-kubeconfig-int128 stdout
    when: setup_kubeconfig_int128.stdout is defined
    ansible.builtin.debug:
      msg: |
        {{ setup_kubeconfig_int128.stdout }}
        {{ setup_kubeconfig_int128.stderr }}

  - name: Fail if local kubeconfig setup fails
    ansible.builtin.fail:
      msg: "Failed to setup local kubeconfig file"
