- name: Post control planes join hooks
  run_once: true
  when:
  - inventory_hostname in groups['control_planes']
  - kubernetes_hookfiles.post_control_planes is defined
  with_items: "{{ kubernetes_hookfiles.post_control_planes }}"
  ansible.builtin.include_tasks: "{{ item }}"
