- name: Enable required kernel modules
  with_items:
  - overlay
  - br_netfilter
  community.general.modprobe:
    name: "{{ item }}"
    persistent: present

- name: Set sysctl's
  with_items:
  - name: fs.inotify.max_user_instances
    value: 8192
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv6.conf.all.disable_ipv6
    value: 1
  - name: vm.overcommit_memory
    value: 1
  - name: kernel.panic_on_oops
    value: 1
  - name: kernel.panic
    value: 10
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    reload: true
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    value: "{{ item.value }}"
