- name: Remove swapfile from /etc/fstab
  with_items:
  - swap
  - none
  ansible.posix.mount:
    fstype: swap
    name: "{{ item }}"
    state: absent

- name: Disable swap
  changed_when: true
  when: ansible_facts["swaptotal_mb"] > 0 and allowswap is not defined
  ansible.builtin.command: swapoff -a
