- name: Restart containerd service
  block:
  - name: Restart containerd service
    ansible.builtin.service:
      name: containerd
      state: restarted

  - name: Wait for 10 seconds for containerd to restart
    ansible.builtin.pause:
      seconds: 10
