- name: Pre proxy configuration hooks
  when: kubernetes_hookfiles.pre_proxies is defined
  with_items: "{{ kubernetes_hookfiles.pre_proxies }}"
  ansible.builtin.include_tasks: "{{ item }}"

- name: Validate Proxy Configuration
  ansible.builtin.assert:
    that:
    - vrrp_interface != None
    - vrrp_password != None
    - vrrp_virtual_router_id != None

- name: Install haproxy
  notify: restart-haproxy
  ansible.builtin.package:
    name:
    - haproxy
    state: present

- name: Copy haproxy.cfg
  notify: restart-haproxy
  ansible.builtin.template:
    src: "{{ kubernetes_proxy_haproxy_config_file }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Configure SELinux for HAProxy (RedHat/Rocky/Alma/Fedora)
  changed_when: false
  when:
  - ansible_facts.os_family == "RedHat"
  - kubernetes_configure_selinux
  ansible.builtin.command:
    cmd: setsebool -P haproxy_connect_any 1

- name: Enable haproxy
  ansible.builtin.systemd_service:
    enabled: true
    name: haproxy

- name: Install keepalived
  notify: restart-keepalived
  when: kubernetes_proxy_enable_keepalived | default(true)
  ansible.builtin.package:
    name:
    - keepalived
    state: present

- name: Copy keepalived.conf
  notify: restart-keepalived
  when: kubernetes_proxy_enable_keepalived | default(true)
  ansible.builtin.template:
    src: "{{ kubernetes_proxy_keepalived_config_file }}"
    dest: /etc/keepalived/keepalived.conf
    owner: root
    mode: '0644'

- name: Enable keepalived
  when: kubernetes_proxy_enable_keepalived | default(true)
  ansible.builtin.systemd_service:
    enabled: true
    name: keepalived

- name: Post proxy configuration hooks
  when: kubernetes_hookfiles.post_proxies is defined
  with_items: "{{ kubernetes_hookfiles.post_proxies }}"
  ansible.builtin.include_tasks: "{{ item }}"
