- name: Pre proxy configuration hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.pre_proxies }}"
  when: kubernetes_hookfiles.pre_proxies is defined

- name: Validate Proxy Configuration
  ansible.builtin.assert:
    that:
    - vrrp_interface != None
    - vrrp_password != None
    - vrrp_virtual_router_id != None

- name: Install haproxy
  notify: restart-haproxy
  ansible.builtin.package:
    name:
    - haproxy
    state: present

- name: Copy haproxy.cfg
  notify: restart-haproxy
  ansible.builtin.template:
    src: "{{ kubernetes_proxy_haproxy_config_file }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Enable haproxy
  ansible.builtin.systemd_service:
    enabled: true
    name: haproxy

- name: Install keepalived
  notify: restart-keepalived
  ansible.builtin.package:
    name:
    - keepalived
    state: present
  when: kubernetes_proxy_enable_keepalived | default(true)

- name: Copy keepalived.conf
  notify: restart-keepalived
  ansible.builtin.template:
    src: "{{ kubernetes_proxy_keepalived_config_file }}"
    dest: /etc/keepalived/keepalived.conf
    owner: root
    mode: '0644'
  when: kubernetes_proxy_enable_keepalived | default(true)

- name: Enable keepalived
  ansible.builtin.systemd_service:
    enabled: true
    name: keepalived
  when: kubernetes_proxy_enable_keepalived | default(true)

- name: Post proxy configuration hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_proxies }}"
  when: kubernetes_hookfiles.post_proxies is defined
