name: Test Kubernetes Installations and Upgrades

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "Test ${{ matrix.os }} - K8s ${{ matrix.scenario.name }}"
    runs-on: ubuntu-24.04
    env:
      DEVCONTAINER: "1"
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-25.10
          - centos9
          - centos10
        scenario:
          - name: "1.33"
            install: "1.33"
            upgrades: []
          - name: "1.34"
            install: "1.34"
            upgrades: []
          - name: "1.35"
            install: "1.35"
            upgrades: []
          - name: "1.33→1.34→1.35"
            install: "1.33"
            upgrades: ["1.34", "1.35"]
          - name: "1.34→1.35"
            install: "1.34"
            upgrades: ["1.35"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable KVM and cloud-tools
        run: |
          set -euxo pipefail
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils cloud-image-utils

          echo "Removing old YQ"
          sudo rm -f $(which yq) || echo "No old yq found by 'which' to remove"
          sudo apt install -y yq

      - name: Check KVM availability
        run: |
          set -euxo pipefail
          ls -la /dev/kvm
          groups
          sudo usermod -a -G kvm $USER

      - name: Install OpenTofu
        run: |
          set -euxo pipefail
          curl -fsSL https://get.opentofu.org/install-opentofu.sh -o /tmp/install-opentofu.sh
          chmod +x /tmp/install-opentofu.sh
          /tmp/install-opentofu.sh --install-method deb

      - name: Configure BIND and add entries for devcontainer
        run: |
          set -euxo pipefail
          sudo apt-get install -y bind9 dnsutils

          # Configure BIND to listen on all interfaces
          sudo rm /etc/bind/*
          sudo cp .devcontainer/bind/* /etc/bind/

          # get first physical network interface
          IFACE=$(ip -o link show | awk -F': ' '/state UP/ {print $2; exit}')
          echo "First physical network interface: ${IFACE}"

          sudo ip a add 172.20.0.10/24 dev ${IFACE}
          
          sudo systemctl restart named

      - name: Create ~/.ssh/devcontainer.id_rsa ssh key
        run: |
          set -euxo pipefail
          mkdir -p ~/.ssh

          # Generate a new SSH key for the devcontainer
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/devcontainer.id_rsa -N '' -C 'devcontainer'

          # Add SSH config entries
          cat << EOF >> ~/.ssh/config
          Host *.k8s.local
              HostName localhost
              IdentityFile ~/.ssh/devcontainer.id_rsa
              StrictHostKeyChecking no
              User ansible
              UserKnownHostsFile /dev/null

          Host px.k8s.local
              Port 2021

          Host cp1.k8s.local
              Port 2022

          Host cp2.k8s.local
              Port 2023

          Host cp3.k8s.local
              Port 2024

          Host w1.k8s.local
              Port 2025

          Host w2.k8s.local
              Port 2026
          EOF

      - name: Run test installation - K8s ${{ matrix.scenario.install }}
        if: toJSON(matrix.scenario.upgrades) == '[]'
        run: |
          set -euxo pipefail
          printenv
          echo "******************************"
          echo "******************************"
          echo "******************************"
          echo "******************************"
          echo "******************************"
          echo "******************************"
          cd test
          mkdir -p .temp
          ./spin-up-test-environment.sh --os-image ${{ matrix.os }} | cat - | tee .temp/spin-up.log
          echo "Finished spinning up test environment, now installing Kubernetes ${{ matrix.scenario.install }}"
          ./install.sh -v ${{ matrix.scenario.install }} | cat - | tee .temp/install.log

      - name: Run upgrade tests
        if: toJSON(matrix.scenario.upgrades) != '[]'
        run: |
          set -euxo pipefail
          UPGRADES='${{ toJson(matrix.scenario.upgrades) }}'
          echo "Upgrades: ${UPGRADES}"

          cd test
          mkdir -p .temp
          ./spin-up-test-environment.sh --os-image ${{ matrix.os }} | cat - | tee .temp/spin-up.log
          echo "Finished spinning up test environment, now installing Kubernetes ${{ matrix.scenario.install }}"
          ./install.sh -v ${{ matrix.scenario.install }} | cat - | tee .temp/install.log
          echo "Will install ${{ matrix.scenario.install }} and upgrade through: ${UPGRADES}"
          echo '${UPGRADES}' | jq -r '.[]' | while read version; do
            echo "Upgrading to Kubernetes $version"
            ./upgrade.sh -v \$version | tee .temp/upgrade-$version.log | cat - | tee .temp/upgrade-${version}.log
            kubectl get nodes
          done

      - name: Collect logs on failure
        if: failure()
        run: |
            set -euxo pipefail
            mkdir -p /tmp/logs/${{ matrix.os }}-${{ matrix.scenario.name }}
            cp test/.temp/*.std* "/tmp/logs/${{ matrix.os }}-${{ matrix.scenario.name }}"/ || true
            cp test/.temp/*.log "/tmp/logs/${{ matrix.os }}-${{ matrix.scenario.name }}"/ || true

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-${{ matrix.scenario.name }}
          path: /tmp/logs/${{ matrix.os }}-${{ matrix.scenario.name }}
          retention-days: 7
